name: python os matrix build #Each job installs Python and prints the version
on:
    push:
        branches: [main]

jobs:
    python-matrix:
        runs-on: ${{  matrix.os  }}

        strategy:
            matrix:
                os: [windows-latest, ubuntu-latest]
                python-version: ["3.10","3.11","3.12"]

        steps:
            - name: install python versions
              uses: actions/setup-python@v4
              with:
                python-version: ${{  matrix.python-version  }}
            - name: print python version
              run: python --version


            
        