name: Multi-OS runners
on:
    push:
        branches: [main]

jobs:
    ubuntu-job:
        runs-on: ubuntu-latest

        steps:
            - name: prints os name
              run: echo "The OS is ${{ runner.os }}"

            - name: prits runners hostname
              run: hostname
              
            - name: prints current user
              run: whoami

    windows-job:                                                 # code here is written in 2 differnt ways
        runs-on: windows-latest
        steps:
            - name: Print Windows info
              run: |
                echo "OS: Windows"
                echo "Hostname: $env:COMPUTERNAME"
                echo "User: $env:USERNAME"
    

    macos-job:
        runs-on: macos-latest

        steps:
            - name: prints os name
              run: echo "The OS is ${{ runner.os }}"

            - name: prits runners hostname
              run: hostname
              
            - name: prints current user
              run: whoami