name: Multi-OS runners
on:
    push:
        branches: [main]

jobs:
    ubuntu-job:
        runs-on: ubuntu-latest

        steps:
            - name: prints os name
              run: echo "The OS is ${{ runner.os }}"

            - name: prits runners hostname
              run: hostname
              
            - name: prints current user
              run: whoami
