name: secrets

on:
    workflow_dispatch

jobs:
    secret-job:
        runs-on: ubuntu-latest
        steps:
            - name: check if secre is set
              env:
                MY_SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
              run: |
                echo "The secret is set: $MY_SECRET_MESSAGE"
            - name: View masked secret
              run: echo "${{ secrets.MY_SECRET_MESSAGE }}" 