name: secrets

on:
    workflow_dispatch

jobs:
    secret-job:
        runs-on: ubuntu-latest
        steps:
            - name: check if secre is set
              env:
                MY_SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
              run: |
                if [ -n "MY_SECRET_MESSAGE" ]; then
                  echo "The secret is set: true"
                else
                  echo "The secret is set: false"
                  exit 1
                fi
            - name: View masked secret
              env:
                MY_SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
              run: |
                echo "If printed, GitHub masks the secret value in logs:"
                echo "${{ secrets.MY_SECRET_MESSAGE }}" 